### ISSUE TITLE
Finding and customizing actions

### ISSUE THREAD

**Issue by iamabear09** [iamabear09/__STUDY__github-action#3]
**공식문서** :: https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions

# Finding and customizing actions
This guide will show you how to **discover, use, and customize actions.**

## [Overview](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#overview)

The actions you use in your workflow can be defined in:
- The same repository as your workflow file
- Any public repository
- A published Docker container image on Docker Hub

GitHub Marketplace
- central location for you to find actions created by the GitHub community.
- [GitHub Marketplace page](https://github.com/marketplace/actions/) enables you to filter for actions by category.

## [Browsing Marketplace actions in the workflow editor](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#browsing-marketplace-actions-in-the-workflow-editor)
- You can search and browse actions directly in your repository's workflow editor.

## [Adding an action to your workflow](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-to-your-workflow)

 add an action
-  by referencing the action in your workflow file.

view the actions referenced in your GitHub Actions workflows
- see “[About the dependency graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph).”

## [Adding an action from GitHub Marketplace](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-github-marketplace)

An action's listing page
- includes the action's version
- the workflow syntax required to use the action.

To keep your workflow stable
- reference the version of the action
  - by specifying the Git or Docker tag number in your workflow file.

 If the action requires you to provide inputs
- set them in your workflow
- see "[Finding and customizing actions](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-inputs-and-outputs-with-an-action)."

## [Adding an action from the same repository](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-the-same-repository)

If an action is defined in the same repository 
- reference the action with either the ‌`{owner}/{repo}@{ref}`
- or `./path/to/dir`
  - The path is relative (`./`) to the default working directory (`github.workspace`, `$GITHUB_WORKSPACE`). 
```
|-- hello-world (repository)
|   |__ .github
|       └── workflows
|           └── my-first-workflow.yml
|       └── actions
|           |__ hello-world-action
|               └── action.yml
```

```
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: My first step - check out repository
        uses: actions/checkout@v4
      # This step references the directory that contains the action.
      - name: Use local hello-world-action
        uses: ./.github/actions/hello-world-action
```

The `action.yml` file is used to provide metadata for the action.
- Learn about the content of this file in "[Metadata syntax for GitHub Actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions)."

## [Adding an action from a different repository](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-a-different-repository)
- reference the action with the `{owner}/{repo}@{ref}` syntax in your workflow file.

## [Referencing a container on Docker Hub](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#referencing-a-container-on-docker-hub)
- reference the action with the `docker://{image}:{tag}` syntax

## [Using inputs and outputs with an action](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-inputs-and-outputs-with-an-action)

An action
-  often accepts or requires inputs 
- and generates outputs that you can use.

```
name: "Example"
description: "Receives file and generates output"
inputs:
  file-path: # id of input
    description: "Path to test script"
    required: true
    default: "test-file.js"
outputs:
  results-file: # id of output
    description: "Path to results file"
```
