### ISSUE TITLE
Essential features of GitHub Actions

### ISSUE THREAD

**Issue by iamabear09** [iamabear09/__STUDY__github-action#4]
## [Overview](https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#overview)

customization techniques
- using variables
- running scripts
- sharing data and artifacts between jobs.

## [Using variables in your workflows](https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#using-variables-in-your-workflows)

GitHub Actions 
- include **default environment** variables
-  you can set **custom environment** variables
   -  in your YAML workflow file.
   -  For more information, see "[Variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)."

Example
  - `POSTGRES_HOST`
  - `POSTGRES_PORT`
  - available to the `node client.js` script.

```
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
```

## [Adding scripts to your workflow](https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#adding-scripts-to-your-workflow)

 `run` keyword
- executed on the assigned runner
- to execute the command `npm install -g bats` on the runner.
```
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g bats
```

 **to run a script stored in your repository** 
-  you must first check out the repository to the runner.
- Having done this, you can use the run keyword to run the script on the runner.

```
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: ./my-script.sh
      - name: Run another script
        run: ./my-other-script.sh
```

setting a default working directory for run commands
- see "[Setting default values for jobs](https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs)."
```
    defaults:
      run:
        working-directory: ./scripts
```

Any scripts must be executable.
- by passing the script as an argument to the interpreter that will run the script
  - `run: bash script.sh`
- or by making the file itself executable
  - `git update-index --chmod=+x PATH/TO/YOUR/script.sh`
- on Linux and Mac runners
  -  you can add a command to give the file the execute permission in the workflow job, prior to running the script:
```
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x my-script.sh my-other-script.sh
      - name: Run the scripts
        run: |
          ./my-script.sh
          ./my-other-script.sh
```
- For more information about the run keyword, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun)."

## [Sharing data between jobs](https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs)

If
-  your job generates files 
  - that you want to share with another job in the same workflow,
-  you want to save the files for later reference

then
- you can store them in GitHub as _artifacts_.

because
- All actions and workflows called within a run 
  - have write access to that run's artifacts.

_Artifacts_ 
- are the files created when you build and test your code.
- might include binary or package files, test results, screenshots, or log files.

For example, you can create a file and then upload it as an artifact.
```
jobs:
  example-job:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
```
For example, you can download the artifact named output-log-file.
```
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
```

To download an artifact from the same workflow run,
- your `download job` should specify `needs: upload-job-name`
- so it doesn't start until the upload job finishes.

> same workflow run 즉, 업로드와 다운로드가 같은 workflow안에 존재하는 경우,
> 당연히 업로드가 완료되고 다운로드를 진행해야 한다.
