### ISSUE TITLE
Contexts

### ISSUE THREAD

**Issue by iamabear09** [iamabear09/__STUDY__github-action#6]
## [About contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts)

Contexts are a way 
- to access information about 
  - workflow runs
  - variables
  - runner environments
  - jobs
  - steps

 Each context
-  is **an object** that contains properties
   - which can be **strings** 
   - or **other objects.** 
- is accessed by using the expression syntax
`${{ <context> }}`
Index syntax: `github['sha']`
Property dereference syntax: `github.sha`

Contexts, objects, and properties will vary significantly under different workflow run conditions.
> Contexts 는 상황에 따라 다르다.

**`github`**
Information about the workflow run.

**`env`**
Contains variables set in a workflow, job, or step. 

**`vars`**
Contains variables set at the repository, organization, or environment levels.

**`job`**
Information about the currently running job

...

## [Determining when to use contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts)

Default environment variables:
- These environment variables exist only on the runner that is executing your job.

Contexts:
- You can use most contexts at any point in your workflow, including when default variables would be unavailable.

```
name: CI
on: push
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/main' }}  #runner에서 실행 전에 참조 된다. (context)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      # runner 존재하는 변수를 참조하게 된다. (default env variable)
```

> 정리
> context는 runner와 상관없이 사용할 수 있다. 하지만, 환경변수는 특정 runner와 관련된 것이다.

## [Context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)

> Contexts는 상황에 따라 다르다. 그러면 언제 어떤 Contexts가 사용이 가능할까?
> 특정 함수 또한, 특정한 상황에서만 사용될 필요성이 있는 경우가 있다.

## 나머지는 Reference이다. 

> 나머지는 reference이므로 나중에 필요할 때 찾아보면 될 것 같다.
