### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by iamabear09** [iamabear09/__STUDY__github-action#7]
## [About variables](https://docs.github.com/en/actions/learn-github-actions/variables#about-variables)

Variables 
- provide a way to store and reuse non-sensitive configuration information
   - compiler flags / usernames / server names
- Commands that run in actions or workflow steps 
   - can create, read, and modify variables.

custom variables
- To define an environment variable in a single workflow,
   - you can use the `env` key in the workflow file.
   - see "[Defining environment variables for a single workflow](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow)".
- To define a configuration variable across multiple workflows,
   - define it at the organization, repository, or environment level
   - see "[Defining configuration variables for multiple workflows](https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows)".

default environment variables
- GitHub sets automatically
- see "[Default environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)".

## [Defining environment variables for a single workflow](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow)

you can define it using the `env` key

The scope of a custom variable set
- The entire workflow
   - by using [env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env) at the top level of the workflow file.
- The contents of a job within a workflow, 
  - by using [jobs.<job_id>.env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv).
- A specific step within a job, 
   - by using [jobs.<job_id>.steps[*].env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv).

```
name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

```

access `env` variable values 
- using runner environment variables or 
- using contexts. 

> runner에 적절한 shell 문법을 사용해야 한다. 또한, runner 환경이 설정 되었을 때, 변수에 접근하는 문법을 사용해야 한다.
> Linux :: `$NAME`
> Window PowerShell :: `$env:NAME`
>
> see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell)."

### [Naming conventions for environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#naming-conventions-for-environment-variables)

❌ default environment variable names ❌
- see "[Default environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)"
- is ignored.

`_PATH` suffix.
- a location on the filesystem 
   - `GITHUB_ENV` and `GITHUB_WORKSPACE` are exceptions

`run: env` in a step
- list the entire set

## [Defining configuration variables for multiple workflows](https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows)

define configuration variables
- [organization](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-organization), 
- [repository](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository),
- [environment](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment) level

> organization 값을 repository 에서 overwrite 가능
> repository 값을 environment에서 overwrite가능
> 우선순위 1. environment ... 2. repository ... 3. organization 

available configuration variables in
- `vars` context
   - "[Using the vars context to access configuration variable values](https://docs.github.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values)". 

### [Configuration variable precedence](https://docs.github.com/en/actions/learn-github-actions/variables#configuration-variable-precedence)

-  the variables from the **caller workflow's repository** are used.
- **Variables from the repository that contains the called workflow are not made available** to the caller workflow
> Caller 와 called workflow의 차이를 모르겠다. 두 개가 다를 수 있나?
> 아! 다른 Repository의 workflow를 사용할 수 있다면 가능 한 얘기인 것 같다.
> 그렇다면 당연해 caller repository의 변수를 사용해야 한다.

### [Naming conventions for configuration variables](https://docs.github.com/en/actions/learn-github-actions/variables#naming-conventions-for-configuration-variables)

Names
- must not start with the GITHUB_ prefix.
- are case insensitive.

> 특별한건 없다. 일반적인 변수 규칙이다.

### [Creating configuration variables for a repository](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository)

create secrets or variables
- admin access / owner access / collaborator access

> 링크 들어가면 설명 잘 나와있다. 

### [Creating configuration variables for an environment](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment)

To create secrets or variables for an environment
- admin access / owner access

> 링크 들어가면 변수 생성하는 방법 잘 나와있다.
For more information on environments, see "[Using environments for deployment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)."

### [Creating configuration variables for an organization](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-organization)

> 링크 들어가면 변수 생성하는 방법 잘 나와있다.

## [Using contexts to access variable values](https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values)

`env` context
- access environment variable values

`vars` context.
- configuration variable values

### [Using the `env` context to access environment variable values](https://docs.github.com/en/actions/learn-github-actions/variables#using-the-env-context-to-access-environment-variable-values)

필요성
- `run` steps 에서는 runner에 의해 처리 되므로 `$NAME` 과 같이 접근 가능
- 하지만, runner에 의해 처리되는 부분이 아니라면 `context`를 사용해서 접근해야 한다.
- the context will be interpolated and replaced by a string before the job is sent to a runner.
- for example
   - `if` conditional which determines whether a job or step is sent to the runner, **is always processed by GitHub Actions.**

```
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
```

```
run: echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ env.DAY_OF_WEEK }}!"
```
> 이렇게 해도 결과는 똑같다. 하지만, 변수를 사용하는 것이 아니라 runner에 전달하기 전에 String으로 변경해서 전달하는 것이다.

### [Using the vars context to access configuration variable values](https://docs.github.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values)

Configuration variables 
- can be accessed across the workflow using `vars` context
- has not been set, 
   - the return will be an empty string.

```
on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "organization variable : $ORGANIZATION_VAR"
        echo "overridden variable : $OVERRIDE_VAR"
        echo "variable from shell environment : $env_var"
      env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
        OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
        
    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
```

## [Default environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)

default environment variables
- are available to every step in a workflow.
-  not accessible through the `env` context.
- 하지만 비슷한 context가 존재한다.

> 나머지는 Reference 이므로 나중에 필요할 때 확인하면 된다.

## [Detecting the operating system](https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system)

```
jobs:
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
```
